version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: api_save
      POSTGRES_PASSWORD: api_pswd
      POSTGRES_DB: character_storage
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
