//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "active_in_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_characters: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_groupe: i32,
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::IdCharacters",
        to = "super::characters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Characters,
    #[sea_orm(
        belongs_to = "super::groupes::Entity",
        from = "Column::IdGroupe",
        to = "super::groupes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Groupes,
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::groupes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groupes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
