//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "current_groupe")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_token: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_groupe: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::groupes::Entity",
        from = "Column::IdGroupe",
        to = "super::groupes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Groupes,
    #[sea_orm(
        belongs_to = "super::tokens::Entity",
        from = "Column::IdToken",
        to = "super::tokens::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tokens,
}

impl Related<super::groupes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groupes.def()
    }
}

impl Related<super::tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
