//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "groupes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub owner_id: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::OwnerId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Accounts,
    #[sea_orm(has_many = "super::invitations::Entity")]
    Invitations,
}

impl Related<super::invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitations.def()
    }
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        super::active_in_groups::Relation::Characters.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::active_in_groups::Relation::Groupes.def().rev())
    }
}

impl Related<super::tokens::Entity> for Entity {
    fn to() -> RelationDef {
        super::current_groupe::Relation::Tokens.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::current_groupe::Relation::Groupes.def().rev())
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        super::groupes_access::Relation::Accounts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::groupes_access::Relation::Groupes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
