//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "invitations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Option<i32>,
    pub groupe_id: Option<i32>,
    pub accepted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::accounts::Entity",
        from = "Column::UserId",
        to = "super::accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Accounts,
    #[sea_orm(
        belongs_to = "super::groupes::Entity",
        from = "Column::GroupeId",
        to = "super::groupes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Groupes,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::groupes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Groupes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
