name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare docker package
      run: docker login rg.fr-par.scw.cloud/cyberpunk-container -u nologin -p ${{ secrets.SCALEWAY_KEY }}
    - name: Build the Docker image
      run: docker build . --tag rg.fr-par.scw.cloud/cyberpunk-container/cyberpunk:latest
    - name: Push the Docker image
      run: docker push rg.fr-par.scw.cloud/cyberpunk-container/cyberpunk:latest
